### ISSUE TITLE
Deleting a version

### ISSUE THREAD

**Issue by davidcittadini** [oortcloud/atmosphere#107]
Hi, I have a package davidcittadini:three published and I have a problem with the different versions.  Therefore, can someone delete version 0.70.0 and keep version 0.14.0?  Thanks for the help :)

**Comment by davidcittadini** [comment]
Actually, if you completely deleted all my packages so that I could do the versioning from the beginning that would be great.  Like everyone, it would be nice if we could manage the package management system ourselves... :)

**Comment by dburles** [comment]
Hey @davidcittadini Meteor's packaging system doesn't support removing packages
