### ISSUE TITLE
Atmosphere.meteor.com is slow

### ISSUE THREAD

**Issue by Whoaa512** [oortcloud/atmosphere#17]
When viewing the main directory, or an individual package, the site seems to stall during loading. I don't know if this is due to the increasing amount of packages or something else, but the site optimization needs another look. :)

**Comment by sylock** [comment]
I also confirm that the search is really slow. I'm on a netbook on Linux. It is an HP 8540p (profesionnal). It's not the fastest computer on earth but not a really slow one either. I also think that the search should be done on server side.
Client driven app are good (that's the point of meteor) but not everything is good to do on the client. You have to deal with a large spectrum of clients (computers), including smartphones. The last ones particularly don't have fast storage.

Which kind of database is used on the client-side?

**Comment by Tarang** [comment]
@sylock Search is now done server side. http://atmosphere.meteor.com is deprecated now in favour of https://atmospherejs.com which is heavily optimised against most of the previous issues that are here.

**Comment by Kestanous** [comment]
I am sure you all are aware but the site really is very slow. On a 2011 macbook pro with solid internet connection the search "test" took 20 seconds to complete. I do like the site but these days its so slow I often just use meteor search.

**Comment by zol** [comment]
Hang tight people, we're working on a major search upgrade that's going to hit sometime today or tomorrow.

**Comment by Kestanous** [comment]
Will do ^_^ keep up the good work.
